### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by bycloudai** [IGLICT/StylizedNeRF#2]
Hi, thanks for sharing the codes from your research.

In the pre-trained model preparation, do you know where I can find the files (vgg_normalised.pth, decoder.pth, vae.pth, etc)? Thanks!

**Comment by kcshum** [comment]
I have tried to find the pretrained pth files. It seems they can be accessed here https://github.com/naoto0804/pytorch-AdaIN for decoder.pth and vgg_normalized.pth. Then you can train with "python train_style_modules.py --task vae" to get vae.pth.

**Comment by yihua7** [comment]
> I have tried to find the pretrained pth files. It seems they can be accessed here https://github.com/naoto0804/pytorch-AdaIN for decoder.pth and vgg_normalized.pth. Then you can train with "python train_style_modules.py --task vae" to get vae.pth.

Absolutely right. Thanks for answering.
