### ISSUE TITLE
Dataset for Stylization

### ISSUE THREAD

**Issue by jdg900** [IGLICT/StylizedNeRF#4]
Hi.

Thank you for sharing your nice work!

I have some questions about the dataset for stylization 

1. Which dataset is used for stylization training?

2. Did you use Wikiart dataset for the style dataset?

3. How many style images did you use for the training?

I'm looking forward to hearing your reply!

Thank you

**Comment by yihua7** [comment]
Hi,
1. Most style images are from _https://www.kaggle.com/datasets/antoinegruson/-wikiart-all-images-120k-link_.
2. Yes. (Above)
3. Usually around 20 style images for a NeRF. More style images require longer training time to converge. If you want to stylize a scene quickly, you can train with a single style image within 10 mins and then render the results.

I hope that would be helpful to you.

**Comment by jdg900** [comment]
Thank you!

**Comment by ShiinaMitsuki** [comment]
> Hi,
> 
> 1. Most style images are from _https://www.kaggle.com/datasets/antoinegruson/-wikiart-all-images-120k-link_.
> 2. Yes. (Above)
> 3. Usually around 20 style images for a NeRF. More style images require longer training time to converge. If you want to stylize a scene quickly, you can train with a single style image within 10 mins and then render the results.
> 
> I hope that would be helpful to you.

Thanks for the reply! 
Could u please provide a copy of the style images used to train the model in the paper?

**Comment by yihua7** [comment]
The copyright of dataset belongs to Kaggle.
You can download it through:
 `wget https://3romcg.bn.files.1drv.com/y4m_wXlfBvwva8k9WU4o0ZeFOACIdLr3dN1zxPtGKNmouKJp9jZW4P5K1dDY2T14xl4lAywbFquMxowH4QrgIC5sNnvOMzkviXvMeQqefFxyC05Xaeov3jNW4OfhaFE_-8rtWzyMTuGxuF5uM1XyE_BPzEXg_M7QKE1zn-fqniAOYYnBPj7GeEqQNDf744Wq2C8PJF7ibbc9S6fKWUKoUPtDQ -O style120_data.zip`
If you have connection issues, let me send it to you by email.

**Comment by ShiinaMitsuki** [comment]
> The copyright of dataset belongs to Kaggle.
> You can download it through:
> `wget https://3romcg.bn.files.1drv.com/y4m_wXlfBvwva8k9WU4o0ZeFOACIdLr3dN1zxPtGKNmouKJp9jZW4P5K1dDY2T14xl4lAywbFquMxowH4QrgIC5sNnvOMzkviXvMeQqefFxyC05Xaeov3jNW4OfhaFE_-8rtWzyMTuGxuF5uM1XyE_BPzEXg_M7QKE1zn-fqniAOYYnBPj7GeEqQNDf744Wq2C8PJF7ibbc9S6fKWUKoUPtDQ -O style120_data.zip`
> If you have connection issues, let me send it to you by email.

Thanks for the reply. I downloaded it successfully.  it has 120 images in total, as for llff dataset, did you just randomly select 20 images from 120 images for a scene to train a nerf?

**Comment by ShiinaMitsuki** [comment]
> The copyright of dataset belongs to Kaggle.
> You can download it through:
> `wget https://3romcg.bn.files.1drv.com/y4m_wXlfBvwva8k9WU4o0ZeFOACIdLr3dN1zxPtGKNmouKJp9jZW4P5K1dDY2T14xl4lAywbFquMxowH4QrgIC5sNnvOMzkviXvMeQqefFxyC05Xaeov3jNW4OfhaFE_-8rtWzyMTuGxuF5uM1XyE_BPzEXg_M7QKE1zn-fqniAOYYnBPj7GeEqQNDf744Wq2C8PJF7ibbc9S6fKWUKoUPtDQ -O style120_data.zip`
> If you have connection issues, let me send it to you by email.

Me again lol.
Could you plz tell me 

- 1. how many style images used to train the VAE in the paper.
- 2. is the style images in the ./small_style (for stylized nerf) a subset of ./all_styles (for VAE)?
