### ISSUE TITLE
Dataset for content

### ISSUE THREAD

**Issue by loveaca-sunlight** [IGLICT/StylizedNeRF#6]
Thanks for the work you share！
I want to know how to generate the content image, that is, the image inside `all_contents` folder that is needed in `finetune_decoder`.
Is it using the original NeRF to directly generate multi-view images?
Are there any additional formatting requirements? 
Can you provide a download of this data?

**Comment by yihua7** [comment]
Hi~ : )
If you are following the readme guidelines to the step of '**Pre-trained Model Preparation**', you can directly use the folder of your training images of NeRF (e.g LLFF dataset's content image folders) as `all_contents`.  There is no additional formatting requirements. Just make sure that 'all_contents' is a folder of pure images.
